# Generated by Django 5.2 on 2025-04-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoCarceraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('faixa_etaria', models.CharField(max_length=50)),
                ('profissao', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('opm', models.CharField(choices=[('4º BPM', '4º BPM'), ('6º BPM', '6º BPM'), ('4ª Cia Ind.', '4ª Cia Ind.')], max_length=20)),
                ('data_fato', models.DateField()),
                ('mes', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('intervalo', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=20)),
                ('dia_semana', models.CharField(max_length=20)),
                ('local_obito', models.CharField(max_length=50)),
                ('cor_pele', models.CharField(max_length=20)),
                ('possui_antecedentes', models.BooleanField()),
                ('causa_fato', models.CharField(max_length=100)),
                ('trafico_posse', models.CharField(max_length=100)),
                ('orcrim', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('historico', models.TextField()),
                ('orgao_registro', models.CharField(max_length=100)),
                ('ano_registro', models.IntegerField()),
                ('numero_registro', models.CharField(max_length=100)),
                ('meio_empregado', models.CharField(max_length=100)),
                ('nome_autor', models.CharField(blank=True, max_length=255, null=True)),
                ('rg_autor', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao_carceraria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.situacaocarceraria')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.tipo')),
            ],
        ),
    ]
