# Generated by Django 5.2 on 2025-04-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
