# Generated by Django 5.2 on 2025-04-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_tipo_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ano',
            field=models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2025', max_length=4),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='faixa_etaria',
            field=models.CharField(choices=[('<1', 'Menos de 1 ano'), ('1-10', 'De 1 até 10 anos'), ('11-20', 'De 11 até 20 anos'), ('21-30', 'De 21 até 30 anos'), ('31-40', 'De 31 até 40 anos'), ('41-50', 'De 41 até 50 anos'), ('51-60', 'De 51 até 60 anos'), ('61-70', 'De 61 até 70 anos'), ('71-80', 'De 71 até 80 anos'), ('81-90', 'De 81 até 90 anos'), ('91-100', 'De 91 até 100 anos'), ('100+', 'Mais de 100 anos'), ('prejudicado', 'Prejudicado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('I', 'Ignorado/Não Informado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.cidade'),
        ),
    ]
