# Generated by Django 5.2 on 2025-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_mes_alter_ocorrencia_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='possui_antecedentes',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('NÃO INFORMADO', 'NÃO INFORMADO')], default='NÃO INFORMADO', max_length=15, null=True),
        ),
    ]
