# Generated by Django 5.2 on 2025-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0006_alter_ocorrencia_possui_antecedentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
